version: 2.1
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: "Updating Golang Version"
          command: |
              wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz
              tar -xvf go1.13.1.linux-amd64.tar.gz
              sudo rm -rf /usr/local/go && sudo mv go /usr/local/
      - run:
          name: "Fetching Deps"
          command: go mod download
      - run:
          name: "Running Tests"
          command: make test
